# Generated by Django 4.1.6 on 2023-02-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newspaper_rename_post_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newspaper',
            new_name='Gazeta',
        ),
        migrations.RenameModel(
            old_name='News',
            new_name='Yangiliklar',
        ),
    ]
