# Generated by Django 4.1.6 on 2023-02-07 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_newspaper_gazeta_rename_news_yangiliklar'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangiliklar',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
